function GetAllDropItems()
{
	return [STDGUN_INUMBER, POWERGUN_INUMBER, SHOTGUN_INUMBER, 
						ROCKET_LAUNCHER_INUMBER, LIFESTEAL_GUN_INUMBER, 
						ROCKETBOOTS_INUMBER, FORCEFIELD_INUMBER, ENERGYFIST_INUMBER,
						DOUBLEHEART_INUMBER, LIGHTNINGBOOTS_INUMBER, REALSHOTGUN_GUN_INUMBER,
						ELECTRIC_GUN_INUMBER, CRUSH_INUMBER, CHARGING_GUN_INUMBER, INFINITYGUN_INUMBER];
}


function GetAllGuns()
{
	return [Gun.STANDART_GUN, Gun.POWERGUN, Gun.SHOTGUN, Gun.ROCKET_LAUNCHER,
			Gun.LIFESTEAL_GUN, Gun.REAL_SHOTGUN, Gun.ELECTRIC_GUN, Gun.CHARGING_GUN];	
}

function GetAllGunsImages()
{
	return [STDGUN_INUMBER, POWERGUN_INUMBER, SHOTGUN_INUMBER, 
						ROCKET_LAUNCHER_INUMBER, LIFESTEAL_GUN_INUMBER, 
						REALSHOTGUN_GUN_INUMBER, ELECTRIC_GUN_INUMBER, CHARGING_GUN_INUMBER];
}


function GetEliteGuns()
{
	return [Gun.POWERGUN, Gun.ROCKET_LAUNCHER, Gun.REAL_SHOTGUN];	
}

function GetEliteGunsImages()
{
	return [POWERGUN_INUMBER, ROCKET_LAUNCHER_INUMBER, REALSHOTGUN_GUN_INUMBER];
}